# -*- coding: utf-8 -*-
"""image sketch

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W-vf8Uh1dWGHO0-IuqTtj23kY8TO9-po
"""

import cv2
import matplotlib.pyplot as plt
from IPython import display

img=cv2.imread('puppy.jpg',0)
display.Image("puppy.jpg",width=250)

print('Minimum color range',img.min())
print('Maximum color range',img.max())

plt.imshow(img,cmap='gray')
plt.title('Black and white imege')
plt.show()

inv=255-img
plt.title('Inverted imege')
plt.imshow(inv,cmap='gray')
plt.show()

gblur=cv2.GaussianBlur(inv,ksize=(21,21),sigmaX=0,sigmaY=0)
plt.title('Imege after Gaussian blur applied')
plt.imshow(gblur,cmap='gray')
plt.show()

dodge= lambda image,mask: cv2.divide(image,255-mask,scale=256)
blended=dodge(img,gblur)
plt.title('Pencil sketch of image')
plt.imshow(blended,cmap='gray')
plt.show()